# PvP Practice Bot - NeoForge mod configuration

# The license for you mod.
license="${mod_license}"

# A list of mods
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/stangler/neoforge-pvpbot-dev-container"

# The authors of the mod
authors="stangler, payor"

# The description text for the mod
description='''
練習用PvPボットモッド。
データパック(mcfunction)のPvP練習ボット機能をNeoForgeでJava移植。
アルティメットクリックスターの練習ボットを、コマンドとGUIで操作可能にしました。
'''

# A dependency
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"